-- Helpdesk Hard Questions
-- https://zh.sqlzoo.net/wiki/Helpdesk_Hard_Questions

-- 11)
-- Show the manager and number of calls received for each hour of the day on 2017-08-12
SELECT Manager, DATE_FORMAT(i.Call_date,'%Y-%m-%d %H') AS Hr, COUNT(*) AS cc
FROM Shift AS sft
JOIN Shift_type AS sftt
ON sft.Shift_type = sftt.Shift_type
JOIN Issue AS i
ON sft.Shift_date = DATE_FORMAT(i.Call_date,'%Y-%m-%d')
WHERE i.call_date BETWEEN '2017-08-12 00:00:00' AND    -- On this specific day
                          '2017-08-12 23:59:59' AND
      DATE_FORMAT(i.Call_date, '%T') >= Start_time AND -- Calls placed between the start and end of a shift
      DATE_FORMAT(i.Call_date, '%T') < End_time
 
GROUP BY Manager, Hr
ORDER BY Manager DESC;

/*
+---------+---------------+----+
| Manager |       Hr      | cc |
+---------+---------------+----+
| LB1     | 2017-08-12 08 |  6 |
| LB1     | 2017-08-12 09 | 16 |
| LB1     | 2017-08-12 10 | 11 |
| LB1     | 2017-08-12 11 |  6 |
| LB1     | 2017-08-12 12 |  8 |
| LB1     | 2017-08-12 13 |  4 |
| AE1     | 2017-08-12 14 | 12 |
| AE1     | 2017-08-12 15 |  8 |
| AE1     | 2017-08-12 16 |  8 |
| AE1     | 2017-08-12 17 |  7 |
| AE1     | 2017-08-12 19 |  5 |
+---------+---------------+----+
*/

-- 12)
-- 80/20 rule. It is said that 80% of the calls are generated by 20% of the callers.
-- Is this true? What percentage of calls are generated by the most active 20% of callers.

-- Skip.

-- 13)
-- Annoying customers. Customers who call in the last five minutes of a shift are annoying.
-- Find the most active customer who has never been annoying.
WITH Calls_per_company (id, name, issueTime) AS
(
  SELECT cst.Company_ref, Company_name, i.Call_date
  FROM Customer AS cst
  JOIN Caller AS clr
  ON cst.Company_ref = clr.Company_ref
  JOIN Issue AS i
  ON clr.Caller_id = i.Caller_id
)

SELECT name AS Company_name, COUNT(*) AS abna
FROM Calls_per_company
WHERE id NOT IN (
  SELECT cpc.id
  FROM Shift AS sft
  JOIN Shift_type AS sftt
  ON sft.Shift_type = sftt.Shift_type
  JOIN Calls_per_company AS cpc
  ON sft.Shift_date = DATE_FORMAT(cpc.issueTime,'%Y-%m-%d')
  WHERE DATE_FORMAT(cpc.issueTime, '%T') BETWEEN
    DATE_SUB(TIME(End_time), INTERVAL 5 MINUTE) AND End_time
)
GROUP BY name
ORDER BY abna DESC
LIMIT 1;

/*
+--------------+------+
| Company_name | abna |
+--------------+------+
| High and Co. |   20 |
+--------------+------+
*/

-- 14)
-- Maximal usage. If every caller registered with a customer makes a call in one day then that customer has
-- "maximal usage" of the service. List the maximal customers for 2017-08-13.
SELECT name AS company_name, caller_count, issue_count
FROM (
  SELECT cst.Company_ref AS id, Company_name AS name, COUNT(*) AS caller_count
  FROM Customer AS cst
  JOIN Caller AS clr
  ON cst.Company_ref = clr.Company_ref
  GROUP BY id, Company_name) AS Callers_per_company
JOIN (
  SELECT Company_ref AS id, COUNT(DISTINCT i.Caller_id) AS issue_count
  FROM Issue AS i
  JOIN Caller AS clr
  ON i.Caller_id = clr.Caller_id
  WHERE Call_date BETWEEN '2017-08-13 00:00:00' AND
                          '2017-08-13 23:59:59'
  GROUP BY id) AS Issues_per_company
ON Callers_per_company.id = Issues_per_company.id
WHERE caller_count = issue_count
ORDER BY Company_name;

/*
+-------------------+--------------+-------------+
|    company_name   | caller_count | issue_count |
+-------------------+--------------+-------------+
| Askew Inc.        |            2 |           2 |
| Bai Services      |            2 |           2 |
| Dasher Services   |            3 |           3 |
| High and Co.      |            5 |           5 |
| Lady Retail       |            4 |           4 |
| Packman Shipping  |            3 |           3 |
| Pitiable Shipping |            2 |           2 |
| Whale Shipping    |            2 |           2 |
+-------------------+--------------+-------------+
*/

-- 15)
-- Consecutive calls occur when an operator deals with two callers within 10 minutes.
-- Find the longest sequence of consecutive calls – give the name of the operator
-- and the first and last call date in the sequence.

-- Skip.